name: Build and tests
on:
  # run tests on push to master, but not when other branches are pushed to
  push:
    branches:
      - master

  # run tests for pull requests to master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test on Linux
    strategy:
      matrix:
        go-version:
          # - 1.12.x
          # - 1.13.x
          # - 1.14.x
          - 1.15.x
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get programs
        run: |
          export GOPROXY=https://proxy.golang.org
          export GOBIN=$HOME/bin

          # build Go tools
          go get github.com/restic/rest-server/...
          go get github.com/restic/calens
          go get github.com/mitchellh/gox

          # minio
          wget -q -O $GOBIN/minio https://dl.minio.io/server/minio/release/linux-amd64/minio
          chmod 755 $GOBIN/minio

      - name: Check out code
        uses: actions/checkout@v1

      # debug with tmate
      # - name: Run apt-get for tmate action
      #   run: sudo apt-get update

      # - name: Debugging with tmate
      #   uses: mxschmitt/action-tmate@v1.0.1

      - name: Build
        run: |
          export PATH=$HOME/bin:$PATH

          rest-server --help
          gox --help
          calens --help
          minio --help

          go run build.go --goos linux
          go run build.go --goos windows
          go run build.go --goos darwin

      - name: Run tests
        run: |
          export PATH=$HOME/bin:$PATH
          go test ./...
